databases:
  - name: jobtool-db
    plan: free               # DB can stay on free for now
    databaseName: jobtool
    user: jobtool

services:
  - type: web
    name: jobtool-web
    runtime: python
    plan: starter            # upgraded from free
    region: oregon

    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install --no-cache-dir -r requirements.txt
      python manage.py migrate --noinput --run-syncdb
      python manage.py collectstatic --noinput

    startCommand: >
      python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker

    autoDeploy: true

    # Add your custom domain once DNS is pointed
    domains:
      - jobs.squire.enterprises

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobtool-db
          property: connectionString
      - fromGroup: django-shared
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: ALLOWED_HOSTS
        value: jobs.squire.enterprises,${RENDER_EXTERNAL_HOSTNAME}
      - key: CSRF_TRUSTED_ORIGINS
        value: https://jobs.squire.enterprises,https://${RENDER_EXTERNAL_HOSTNAME}

envVarGroups:
  - name: django-shared
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
```

